# PREGUNTA 4
## Aplique MapReduce para llevar esos datos a una base de datos NoSQL que permita agrupar el número de programadores por lenguaje de programación y las respuestas por pregunta de los 5 conjuntos en paralelo* (Mediante Map Reduce).  (Adjunte la rutina en Python, SQL y/o Javascript que le permitió obtener la base de datos SQL en paralelo, deberá adjuntar evidencia del procesamiento en paralelo y hará parte de la exposición la demostración de la rutina)

#### Primero se unen los archivos json en uno solo
Se usa pandas para leer los archivo y para exportarlos de nuevo

In [ ]:
import json
import pandas as pd
import os

In [39]:
data1 = pd.read_json(r'.\Base_Datos_Encuestas\BD_Encuesta_0_16000.json')
data2 = pd.read_json(r'.\Base_Datos_Encuestas\BD_Encuesta_16000_32000.json')
data3 = pd.read_json(r'.\Base_Datos_Encuestas\BD_Encuesta_32000_48000.json')
data4 = pd.read_json(r'.\Base_Datos_Encuestas\BD_Encuesta_48000_64000.json')
data5 = pd.read_json(r'.\Base_Datos_Encuestas\BD_Encuesta_64000_80000.json')
data6 = pd.read_json(r'.\Base_Datos_Encuestas\BD_Encuesta_80000_96000.json')
data7 = pd.read_json(r'.\Base_Datos_Encuestas\BD_Encuesta_96000_112000.json')
data8 = pd.read_json(r'.\Base_Datos_Encuestas\BD_Encuesta_112000_128000.json')
data9 = pd.read_json(r'.\Base_Datos_Encuestas\BD_Encuesta_128000_144000.json')
data10 = pd.read_json(r'.\Base_Datos_Encuestas\BD_Encuesta_144000_160000.json')
data11 = pd.read_json(r'.\Base_Datos_Encuestas\BD_Encuesta_160000_160111.json')

In [40]:
data1.shape

(16000, 24)

In [41]:
data10.head(5)

,AngularJS,C,CPlusPlus,CSS,CSharp,HTML5,Id_Age,Id_Country,Id_Experience,Id_Gender,...,ObjectiveC,PHP,Perl,Python,Ruby,SQL,SQL_Server,TypeScript,Year,jQuery
0,NaN,None,None,NaN,C#,NaN,NaN,33,6.0,4,...,None,None,None,None,None,None,NaN,None,2017,NaN
1,NaN,None,None,NaN,None,NaN,NaN,36,6.0,2,...,None,None,None,None,Ruby,None,NaN,None,2017,NaN
2,NaN,None,None,NaN,None,NaN,NaN,165,6.0,4,...,None,None,None,None,None,None,NaN,None,2017,NaN
3,NaN,None,None,NaN,C#,NaN,NaN,213,6.0,2,...,None,None,None,None,None,SQL,NaN,None,2017,NaN
4,NaN,None,None,NaN,C#,NaN,NaN,212,6.0,2,...,None,None,None,None,None,SQL,NaN,None,2017,NaN

In [42]:
Total = pd.concat([data1, data2, data3, data4, data5, data6, data7, data8, data9, data10], axis=0)

In [43]:
Total.shape

(160000, 24)

In [30]:
Total.tail()

,AngularJS,C,CPlusPlus,CSS,CSharp,HTML5,Id_Age,Id_Country,Id_Experience,Id_Gender,...,ObjectiveC,PHP,Perl,Python,Ruby,SQL,SQL_Server,TypeScript,Year,jQuery
15995,NaN,None,None,NaN,None,NaN,NaN,210.0,4.0,4.0,...,None,None,None,None,None,None,NaN,None,2017,NaN
15996,NaN,None,None,NaN,None,NaN,NaN,213.0,6.0,4.0,...,None,None,None,None,None,None,NaN,None,2017,NaN
15997,NaN,None,None,NaN,C#,NaN,NaN,213.0,5.0,2.0,...,Objective-C,None,None,None,None,SQL,NaN,TypeScript,2017,NaN
15998,NaN,None,None,NaN,C#,NaN,NaN,56.0,6.0,2.0,...,None,None,None,None,None,SQL,NaN,TypeScript,2017,NaN
15999,NaN,None,None,NaN,C#,NaN,NaN,213.0,5.0,2.0,...,None,None,None,None,None,SQL,NaN,None,2017,NaN

In [31]:
Total = Total.reset_index()

In [34]:
Total = Total.drop(['index'], axis=1)

In [47]:
Total.tail(300)

,AngularJS,C,CPlusPlus,CSS,CSharp,HTML5,Id_Age,Id_Country,Id_Experience,Id_Gender,...,ObjectiveC,PHP,Perl,Python,Ruby,SQL,SQL_Server,TypeScript,Year,jQuery
15700,NaN,C,C++,NaN,None,NaN,NaN,93.0,6.0,2.0,...,None,PHP,None,Python,None,SQL,NaN,None,2017,NaN
15701,NaN,None,None,NaN,C#,NaN,NaN,213.0,6.0,2.0,...,None,PHP,None,Python,None,SQL,NaN,None,2017,NaN
15702,NaN,None,None,NaN,None,NaN,NaN,78.0,6.0,4.0,...,None,None,None,None,None,None,NaN,None,2017,NaN
15703,NaN,None,None,NaN,None,NaN,NaN,94.0,4.0,4.0,...,None,None,None,None,None,None,NaN,None,2017,NaN
15704,NaN,None,None,NaN,None,NaN,NaN,78.0,4.0,4.0,...,None,None,None,None,None,None,NaN,None,2017,NaN
15705,NaN,None,None,NaN,None,NaN,NaN,93.0,5.0,4.0,...,None,None,None,None,None,None,NaN,None,2017,NaN
15706,NaN,C,C++,NaN,C#,NaN,NaN,130.0,6.0,2.0,...,Objective-C,PHP,None,None,None,SQL,NaN,None,2017,NaN
15707,NaN,None,None,NaN,None,NaN,NaN,190.0,6.0,4.0,...,None,None,None,None,None,None,NaN,None,2017,NaN
15708,NaN,None,None,NaN,C#,NaN,NaN,191.0,4.0,2.0,...,None,None,None,None,None,SQL,NaN,None,2017,NaN
15709,NaN,None,None,NaN,C#,NaN,NaN,42.0,6.0,2.0,...,None,PHP,None,None,None,SQL,NaN,None,2017,NaN
15710,NaN,None,C++,NaN,C#,NaN,NaN,213.0,6.0,2.0,...,None,None,None,None,None,SQL,NaN,None,2017,NaN
15711,NaN,None,None,NaN,C#,NaN,NaN,144.0,6.0,2.0,...,Objective-C,PHP,None,Python,None,SQL,NaN,None,2017,NaN
15712,NaN,None,None,NaN,None,NaN,NaN,213.0,5.0,4.0,...,None,PHP,None,None,None,SQL,NaN,None,2017,NaN
15713,NaN,None,None,NaN,None,NaN,NaN,93.0,4.0,4.0,...,None,None,None,None,None,None,NaN,None,2017,NaN
15714,NaN,None,None,NaN,None,NaN,NaN,144.0,6.0,2.0,...,None,PHP,None,None,None,SQL,NaN,None,2017,NaN
15715,NaN,None,None,NaN,C#,NaN,NaN,60.0,4.0,2.0,...,None,PHP,None,Python,None,SQL,NaN,None,2017,NaN
15716,NaN,None,None,NaN,None,NaN,NaN,213.0,4.0,4.0,...,None,None,None,None,None,None,NaN,None,2017,NaN
15717,NaN,None,C++,NaN,C#,NaN,NaN,144.0,6.0,2.0,...,None,None,None,None,None,None,NaN,None,2017,NaN
15718,NaN,None,C++,NaN,None,NaN,NaN,213.0,5.0,2.0,...,Objective-C,None,None,Python,Ruby,None,NaN,None,2017,NaN
15719,NaN,None,C++,NaN,C#,NaN,NaN,137.0,6.0,2.0,...,None,None,None,None,None,None,NaN,None,2017,NaN
15720,NaN,C,None,NaN,None,NaN,NaN,162.0,6.0,2.0,...,None,None,Perl,None,None,SQL,NaN,None,2017,NaN
15721,NaN,None,None,NaN,C#,NaN,NaN,145.0,6.0,2.0,...,None,None,None,None,None,SQL,NaN,TypeScript,2017,NaN
15722,NaN,None,None,NaN,None,NaN,NaN,93.0,5.0,4.0,...,None,None,None,None,None,None,NaN,None,2017,NaN
15723,NaN,C,C++,NaN,C#,NaN,NaN,227.0,6.0,2.0,...,Objective-C,PHP,Perl,None,None,SQL,NaN,TypeScript,2017,NaN
15724,NaN,None,None,NaN,None,NaN,NaN,42.0,6.0,4.0,...,None,None,None,None,None,None,NaN,None,2017,NaN
15725,NaN,C,C++,NaN,C#,NaN,NaN,213.0,6.0,2.0,...,None,None,None,Python,None,None,NaN,None,2017,NaN
15726,NaN,None,None,NaN,None,NaN,NaN,213.0,6.0,4.0,...,None,None,None,None,None,None,NaN,None,2017,NaN
15727,NaN,C,C++,NaN,C#,NaN,NaN,209.0,4.0,4.0,...,Objective-C,PHP,None,Python,Ruby,SQL,NaN,None,2017,NaN
15728,NaN,None,None,NaN,C#,NaN,NaN,84.0,6.0,2.0,...,None,PHP,None,None,None,SQL,NaN,None,2017,NaN
15729,NaN,C,None,NaN,None,NaN,NaN,78.0,6.0,2.0,...,None,PHP,Perl,None,None,SQL,NaN,None,2017,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15970,NaN,C,C++,NaN,None,NaN,NaN,78.0,6.0,2.0,...,None,PHP,Perl,Python,Ruby,SQL,NaN,TypeScript,2017,NaN
15971,NaN,None,None,NaN,None,NaN,NaN,212.0,6.0,4.0,...,None,None,None,None,None,None,NaN,None,2017,NaN
15972,NaN,None,None,NaN,C#,NaN,NaN,213.0,6.0,2.0,...,None,PHP,None,None,None,SQL,NaN,None,2017,NaN
15973,NaN,None,C++,NaN,None,NaN,NaN,212.0,6.0,4.0,...,None,None,None,Python,None,SQL,NaN,None,2017,NaN
15974,NaN,C,None,NaN,None,NaN,NaN,49.0,3.0,4.0,...,None,PHP,None,None,None,SQL,NaN,None,2017,NaN
15975,NaN,None,C++,NaN,C#,NaN,NaN,213.0,6.0,2.0,...,Objective-C,PHP,Perl,Python,Ruby,SQL,NaN,TypeScript,2017,NaN
15976,NaN,None,None,NaN,None,NaN,NaN,213.0,NaN,4.0,...,None,None,None,None,None,None,NaN,None,2017,NaN
15977,NaN,None,None,NaN,None,NaN,NaN,191.0,6.0,4.0,...,None,None,None,None,None,None,NaN,None,2017,NaN
15978,NaN,None,None,NaN,C#,NaN,NaN,212.0,6.0,2.0,...,None,PHP,None,None,None,SQL,NaN,TypeScript,2017,NaN
15979,NaN,None,C++,NaN,None,NaN,NaN,42.0,6.0,2.0,...,None,PHP,Perl,Python,None,SQL,NaN,None,2017,NaN
15980,NaN,None,None,NaN,None,NaN,NaN,16.0,6.0,4.0,...,None,None,None,None,None,None,NaN,None,2017,NaN
15981,NaN,None,C++,NaN,C#,NaN,NaN,188.0,6.0,2.0,...,None,PHP,Perl,Python,None,SQL,NaN,None,2017,NaN
15982,NaN,None,None,NaN,None,NaN,NaN,74.0,6.0,2.0,...,None,PHP,Perl,None,None,SQL,NaN,None,2017,NaN
15983,NaN,None,None,NaN,None,NaN,NaN,59.0,6.0,4.0,...,None,None,None,None,None,None,NaN,None,2017,NaN
15984,NaN,C,None,NaN,None,NaN,NaN,213.0,6.0,2.0,...,None,None,Perl,Python,None,None,NaN,None,2017,NaN
15985,NaN,None,None,NaN,None,NaN,NaN,60.0,6.0,4.0,...,None,None,None,None,None,None,NaN,None,2017,NaN
15986,NaN,C,C++,NaN,C#,NaN,NaN,42.0,6.0,2.0,...,None,PHP,None,None,None,SQL,NaN,None,2017,NaN
15987,NaN,None,C++,NaN,C#,NaN,NaN,212.0,6.0,2.0,...,None,None,None,Python,None,SQL,NaN,TypeScript,2017,NaN
15988,NaN,None,None,NaN,None,NaN,NaN,130.0,6.0,4.0,...,None,None,None,None,None,None,NaN,None,2017,NaN
15989,NaN,None,None,NaN,None,NaN,NaN,74.0,3.0,4.0,...,None,None,None,None,None,None,NaN,None,2017,NaN
15990,NaN,None,None,NaN,None,NaN,NaN,73.0,6.0,2.0,...,None,None,None,Python,None,SQL,NaN,None,2017,NaN
15991,NaN,None,None,NaN,None,NaN,NaN,212.0,6.0,2.0,...,None,PHP,None,Python,Ruby,SQL,NaN,None,2017,NaN
15992,NaN,None,C++,NaN,None,NaN,NaN,78.0,6.0,2.0,...,Objective-C,PHP,Perl,Python,Ruby,SQL,NaN,None,2017,NaN
15993,NaN,None,None,NaN,None,NaN,NaN,66.0,5.0,4.0,...,None,None,None,None,None,None,NaN,None,2017,NaN
15994,NaN,None,None,NaN,None,NaN,NaN,213.0,6.0,4.0,...,None,None,None,None,None,None,NaN,None,2017,NaN
15995,NaN,None,None,NaN,None,NaN,NaN,210.0,4.0,4.0,...,None,None,None,None,None,None,NaN,None,2017,NaN
15996,NaN,None,None,NaN,None,NaN,NaN,213.0,6.0,4.0,...,None,None,None,None,None,None,NaN,None,2017,NaN
15997,NaN,None,None,NaN,C#,NaN,NaN,213.0,5.0,2.0,...,Objective-C,None,None,None,None,SQL,NaN,TypeScript,2017,NaN
15998,NaN,None,None,NaN,C#,NaN,NaN,56.0,6.0,2.0,...,None,None,None,None,None,SQL,NaN,TypeScript,2017,NaN
15999,NaN,None,None,NaN,C#,NaN,NaN,213.0,5.0,2.0,...,None,None,None,None,None,SQL,NaN,None,2017,NaN

In [38]:
Total.to_json(r'.\Base_Datos_Encuestas\Total_DBv0json', orient='values')

A continuación se carga el archivo json unificado a la base de datos en Mongodb

C:\>mongoimport.exe --db taller_MDB --collection bodega --file C:\Total_DB.json --jsonArray

<img src="./img/load_mongo.PNG">

Luego se realiza la conexión del cliente mongo con el servidor mongod.

la base de datos se llama taller_MDB y la colección se llama bodega, se cargaron 160.111 documentos:

<img src="./img/load_mongo1.PNG">

Luego se generan con javascript las funciones map y reduce para responder a la pregunta:  numero de programadores por lenguaje de programación?

Numero de programadores de AngularJS:  8.842

<img src="./img/Mongo_conteo_AngularJS.PNG">


Numero de programadores de C:  18.560



<img src="./img/Mongo_conteo_C.PNG">



Numero de programadores de C++: 27.693



<img src="./img/Mongo_conteo_C++.PNG">


Numero de programadores de CSS: 4.364



<img src="./img/Mongo_conteo_CSS.PNG">


Numero de programadores de C#: 43.961



<img src="./img/Mongo_conteo_C#.PNG">


Numero de programadores de HTML5: 2.187



<img src="./img/Mongo_conteo_HTML5.PNG">


Numero de programadores de ObjectiveC: 9.583



<img src="./img/Mongo_conteo_ObjectiveC.PNG">
 


Numero de programadores de PHP: 36.341



<img src="./img/Mongo_conteo_PHP.PNG">


Numero de programadores de Perl: 4.941



<img src="./img/Mongo_conteo_Perl.PNG">


Numero de programadores de Python: 34.430



<img src="./img/Mongo_conteo_Python.PNG">



Numero de programadores de Ruby: 11.748



<img src="./img/Mongo_conteo_Ruby.PNG">


Numero de programadores de SQL: 65.467



<img src="./img/Mongo_conteo_SQL.PNG">


Numero de programadores de SQL_Server: 13.435


<img src="./img/Mongo_conteo_SQL_Server.PNG">


Numero de programadores de TypeScript:  3.565



<img src="./img/Mongo_conteo_TypeScript.PNG">


Numero de programadores de jQuery: 4.193



<img src="./img/Mongo_conteo_jQuery.PNG">

### En resumen, durante los 7 años de encuestas, estos son los programadores por programa

Numero de programadores de SQL: 65.467

Numero de programadores de C#: 43.961

Numero de programadores de PHP: 36.341

Numero de programadores de Python: 34.430

Numero de programadores de C++: 27.693

Numero de programadores de C:  18.560

Numero de programadores de SQL_Server: 13.435

Numero de programadores de Ruby: 11.748

Numero de programadores de ObjectiveC: 9.583

Numero de programadores de AngularJS:  8.842

Numero de programadores de CSS: 4.364

Numero de programadores de Perl: 4.941

Numero de programadores de jQuery: 4.193

Numero de programadores de TypeScript:  3.565

Numero de programadores de HTML5: 2.187